---
title: "Hadron Physics"
subtitle: "Summer Semester 2024 - Ruhr University Bochum"
---

# Welcome to Hadron Physics

This course covers the fundamental principles of hadron physics, exploring the strong interactions that govern the behavior of quarks and gluons.

## Course Structure

The lectures are organized chronologically by year:

### 2025 Lectures
- [Lecture 1](2025-Lecture-01.html) - Lecture 1
- [Lecture 2](2025-Lecture-02.html) - Lecture 2
- [Lecture 3](2025-Lecture-03.html) - Lecture 3

### 2024 Lectures
- [Lecture 1](2024-Lecture-01.html) - Lecture 1
- [Lecture 2](2024-Lecture-02.html) - Lecture 2
- [Lecture 3](2024-Lecture-03.html) - Lecture 3
- [Lecture 4](2024-Lecture-04.html) - Lecture 4
- [Lecture 5](2024-Lecture-05.html) - Lecture 5
- [Lecture 6](2024-Lecture-06.html) - Lecture 6
- [Lecture 7](2024-Lecture-07.html) - Lecture 7
- [Lecture 8](2024-Lecture-08.html) - Lecture 8
- [Lecture 10](2024-Lecture-10.html) - Lecture 10
- [Lecture 11](2024-Lecture-11.html) - Lecture 11
- [Lecture 12](2024-Lecture-12.html) - Lecture 12

## Resources

- [GitHub Repository](https://github.com/mmikhasenko/LM-Notes-HadronPhysics)
- [Moodle Course](https://moodle.ruhr-uni-bochum.de/course/view.php?id=58809)
